/**
 * Agent and script runner for workflows.
 *
 * Replaces the old handler system. Instead of loading TypeScript handlers,
 * spawns agents via `pi --print` or runs scripts directly.
 *
 * The agent is the brain — it has tools (read, write, bash) and does everything.
 * This module just spawns it and captures results.
 */

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, createWriteStream } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { info, error, debug } from "./logger.js";
import { setTaskPid } from "./queue.js";
import { loadConfig as loadAgentsConfig } from "../../pi-agents/src/config.js";
import { resolveModel } from "../../pi-agents/src/models.js";
import { buildAgentEnv } from "../../pi-agents/src/env.js";
import { runValidators } from "./validators.js";
import type { WorkflowConfig } from "./workflows.js";

const PI_PATH = process.env.BOSUN_PI_PATH || "pi";
const STATE_DIR = process.env.BOSUN_DAEMON_STATE || ".bosun-daemon";

/** Get the log file path for a workflow run. Overwrites each run. */
function workflowLogPath(name: string): string {
  return join(process.cwd(), STATE_DIR, "logs", `${name}.log`);
}

// Lazy-load models from .pi/agents.json on first use (generated by `just init`).
// Deferred so process.cwd() is evaluated at runtime, not import time.
let _models: Record<string, string> | null = null;
function getModels(): Record<string, string> {
  if (!_models) {
    _models = loadAgentsConfig(process.cwd()).models;
  }
  return _models;
}

export interface RunResult {
  exitCode: number;
  stdout: string;
  stderr: string;
  skipped: boolean;
  validationPassed: boolean;
  attempts: number;
}

interface RunContext {
  /** Trigger paths (from file watcher). */
  paths?: string[];
  /** Date string (for scheduled workflows). */
  date?: string;
  /** Additional context from the rule engine. */
  [key: string]: unknown;
}

/**
 * Run a workflow: validate input → spawn agent/script → validate output → retry if needed.
 */
export async function runWorkflow(
  workflow: WorkflowConfig,
  context: RunContext,
): Promise<RunResult> {
  const result: RunResult = {
    exitCode: -1,
    stdout: "",
    stderr: "",
    skipped: false,
    validationPassed: false,
    attempts: 0,
  };

  // --- Input validation ---
  if (workflow.validators.input) {
    const inputValid = await runValidators(
      "input",
      join(workflow.dir, workflow.validators.input),
      { workflow, context, stdout: "", exitCode: 0 },
    );
    if (!inputValid.passed) {
      info(`[${workflow.name}] Input validation failed, skipping: ${inputValid.stderr}`);
      result.skipped = true;
      return result;
    }
    debug(`[${workflow.name}] Input validation passed`);
  }

  // --- Run with retries ---
  let lastValidatorFeedback = "";

  for (let attempt = 1; attempt <= workflow.retry.max_attempts; attempt++) {
    result.attempts = attempt;
    info(`[${workflow.name}] Running (attempt ${attempt}/${workflow.retry.max_attempts})`);

    let runResult: { exitCode: number; stdout: string; stderr: string };

    if (workflow.type === "agent") {
      runResult = await spawnAgent(workflow, context, lastValidatorFeedback);
    } else {
      runResult = await runScript(workflow, context);
    }

    result.exitCode = runResult.exitCode;
    result.stdout = runResult.stdout;
    result.stderr = runResult.stderr;

    if (runResult.exitCode !== 0) {
      error(`[${workflow.name}] Exited with code ${runResult.exitCode}`);
      if (attempt < workflow.retry.max_attempts) {
        lastValidatorFeedback = `Process exited with code ${runResult.exitCode}: ${runResult.stderr}`;
        continue;
      }
      return result;
    }

    // --- Output validation ---
    if (workflow.validators.output) {
      const outputValid = await runValidators(
        "output",
        join(workflow.dir, workflow.validators.output),
        { workflow, context, stdout: runResult.stdout, exitCode: runResult.exitCode },
      );

      if (!outputValid.passed) {
        error(`[${workflow.name}] Output validation failed: ${outputValid.stderr}`);
        if (attempt < workflow.retry.max_attempts && workflow.retry.feedback) {
          lastValidatorFeedback = outputValid.stderr;
          info(`[${workflow.name}] Will retry with validator feedback`);
          continue;
        }
        return result;
      }
      debug(`[${workflow.name}] Output validation passed`);
    }

    // Success
    result.validationPassed = true;
    info(`[${workflow.name}] Completed successfully`);
    return result;
  }

  return result;
}

/**
 * Spawn a pi agent in --print mode.
 */
async function spawnAgent(
  workflow: WorkflowConfig,
  context: RunContext,
  validatorFeedback: string,
): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  const model = resolveModel(workflow.agent?.model, getModels());
  // --no-extensions disables all extensions including pi-sandbox.
  // Daemon workflows are trusted system tasks — sandboxing blocks
  // filesystem writes that workflow agents need (e.g., writing analysis JSON).
  const args: string[] = ["--print", "--no-extensions", "--model", model];

  // Agent system prompt
  if (workflow.agent?.systemPromptFile && existsSync(workflow.agent.systemPromptFile)) {
    args.push("--append-system-prompt", workflow.agent.systemPromptFile);
  }

  // Build task prompt
  let prompt = workflow.agent?.prompt || "Run the workflow task.";

  // Append validator feedback for retries
  if (validatorFeedback) {
    prompt += `\n\n[Previous attempt failed validation]\nValidator feedback: ${validatorFeedback}\nPlease fix the issue and try again.`;
  }

  args.push(prompt);

  const env: Record<string, string> = {
    ...process.env as Record<string, string>,
    ...buildAgentEnv({ agent: workflow.name, name: workflow.name }),
    BOSUN_DAEMON: "1",
    WORKFLOW_NAME: workflow.name,
    WORKFLOW_DIR: workflow.dir,
  };

  // Add trigger context
  if (context.date) env.WORKFLOW_DATE = context.date;
  if (context.paths?.length) env.WORKFLOW_PATHS = context.paths.join(",");

  const timeoutMs = workflow.timeout_minutes * 60 * 1000;

  const logFile = workflowLogPath(workflow.name);
  const taskId = context._task_id as string | undefined;
  return spawnProcess(PI_PATH, args, {
    cwd: process.cwd(),
    env,
    timeoutMs,
    logFile,
    taskId,
  });
}

/**
 * Run a script workflow.
 */
async function runScript(
  workflow: WorkflowConfig,
  context: RunContext,
): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  if (!workflow.script?.command) {
    return { exitCode: 1, stdout: "", stderr: "No script command configured" };
  }

  const command = resolve(workflow.dir, workflow.script.command);
  if (!existsSync(command)) {
    return { exitCode: 1, stdout: "", stderr: `Script not found: ${command}` };
  }

  const env: Record<string, string> = {
    ...process.env as Record<string, string>,
    BOSUN_DAEMON: "1",
    WORKFLOW_NAME: workflow.name,
    WORKFLOW_DIR: workflow.dir,
  };

  if (context.date) env.WORKFLOW_DATE = context.date;
  if (context.paths?.length) env.WORKFLOW_PATHS = context.paths.join(",");

  const timeoutMs = workflow.timeout_minutes * 60 * 1000;

  const logFile = workflowLogPath(workflow.name);
  const taskId = context._task_id as string | undefined;
  return spawnProcess("bun", [command], {
    cwd: process.cwd(),
    env,
    timeoutMs,
    logFile,
    taskId,
  });
}

/**
 * Spawn a process, track its PID, and write output to a log file.
 */
function spawnProcess(
  cmd: string,
  args: string[],
  opts: { cwd: string; env: Record<string, string>; timeoutMs: number; logFile?: string; taskId?: string },
): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const proc = spawn(cmd, args, {
      cwd: opts.cwd,
      env: opts.env,
      stdio: ["ignore", "pipe", "pipe"],
    });

    // Track PID in queue for liveness checks (scoped to specific task)
    if (proc.pid && opts.taskId) {
      setTaskPid(opts.taskId, proc.pid);
    }

    let stdout = "";
    let stderr = "";

    // Stream output to log file if provided
    let logStream: import("node:fs").WriteStream | null = null;
    if (opts.logFile) {
      try {
        mkdirSync(dirname(opts.logFile), { recursive: true });
        logStream = createWriteStream(opts.logFile, { flags: "w" });
        logStream.write(`[${new Date().toISOString()}] PID: ${proc.pid}\n`);
        logStream.write(`[${new Date().toISOString()}] CMD: ${cmd} ${args.slice(0, 3).join(" ")}...\n\n`);
      } catch {}
    }

    proc.stdout.on("data", (d) => {
      const chunk = d.toString();
      stdout += chunk;
      logStream?.write(chunk);
    });
    proc.stderr.on("data", (d) => {
      const chunk = d.toString();
      stderr += chunk;
      logStream?.write(`[stderr] ${chunk}`);
    });

    const timeout = setTimeout(() => {
      proc.kill("SIGTERM");
      setTimeout(() => proc.kill("SIGKILL"), 5000);
      logStream?.write(`\n[${new Date().toISOString()}] TIMEOUT\n`);
      logStream?.end();
      resolve({ exitCode: 124, stdout, stderr: stderr + "\nTimeout exceeded" });
    }, opts.timeoutMs);

    proc.on("error", (err) => {
      clearTimeout(timeout);
      logStream?.write(`\n[${new Date().toISOString()}] ERROR: ${err.message}\n`);
      logStream?.end();
      resolve({ exitCode: 127, stdout, stderr: err.message });
    });

    proc.on("exit", (code) => {
      clearTimeout(timeout);
      logStream?.write(`\n[${new Date().toISOString()}] EXIT: ${code}\n`);
      logStream?.end();
      resolve({ exitCode: code ?? 1, stdout, stderr });
    });
  });
}
